import type { Discipline, User, LeaderboardEntry, DailyStats } from '@/types'

export const mockUser: User = {
  id: 'user-1',
  name: 'Marina',
  level: 8,
  xp: 3420,
  xpForNextLevel: 4000,
  streak: 7,
  longestStreak: 14,
  totalStudyMinutes: 1840,
  joinedAt: new Date('2024-09-01'),
  badges: [
    { id: 'b1', name: 'Primeira Aula', description: 'Completaste a tua primeira aula', icon: '🎓', rarity: 'common', unlockedAt: new Date('2024-09-01') },
    { id: 'b2', name: 'Semana Perfeita', description: '7 dias consecutivos de estudo', icon: '🔥', rarity: 'rare', unlockedAt: new Date('2024-09-08') },
    { id: 'b3', name: 'Quiz Master', description: '10 quizzes com 100%', icon: '⚡', rarity: 'epic', unlockedAt: new Date('2024-09-15') },
    { id: 'b4', name: 'Madrugador', description: 'Estudaste antes das 7h', icon: '🌅', rarity: 'common' },
    { id: 'b5', name: 'Lenda', description: 'Nível 10 atingido', icon: '👑', rarity: 'legendary' },
  ],
}

export const mockDisciplines: Discipline[] = [
  {
    id: 'hgp-6',
    name: 'HGP',
    subject: 'História e Geografia de Portugal',
    year: 6,
    color: '#3b82f6',
    icon: '🗺️',
    examDate: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000), // 28 days from now
    totalLessons: 48,
    completedLessons: 19,
    topics: [
      {
        id: 't1',
        disciplineId: 'hgp-6',
        title: 'Portugal no século XIII',
        description: 'A formação do reino de Portugal e a consolidação das fronteiras.',
        order: 1,
        isUnlocked: true,
        completedAt: new Date('2024-10-01'),
        lessons: [
          {
            id: 'l1',
            topicId: 't1',
            title: 'A Formação de Portugal',
            type: 'text',
            difficulty: 'basico',
            estimatedMinutes: 15,
            xpReward: 50,
            isCompleted: true,
            completedAt: new Date('2024-10-01'),
            score: 100,
            content: {
              type: 'text',
              body: `## A Formação do Reino de Portugal\n\nPortugal é um dos países mais antigos da Europa, com fronteiras praticamente inalteradas desde o século XIII.\n\n### Condado Portucalense\nO território que viria a ser Portugal surgiu como o **Condado Portucalense**, doado por Afonso VI de Leão a **D. Henrique de Borgonha** em 1096.\n\n### D. Afonso Henriques\nO filho de D. Henrique, **D. Afonso Henriques**, proclamou a independência de Portugal em **1143** pelo Tratado de Zamora, tornando-se o primeiro rei de Portugal.\n\n### Batalha de Ourique (1139)\nSegundo a tradição, antes desta batalha contra os mouros, Cristo terá aparecido a D. Afonso Henriques — episódio que ficou conhecido como o **Milagre de Ourique**.\n\n> **Resumo:** Portugal tornou-se reino independente em 1143, com D. Afonso Henriques como primeiro monarca.`,
              keyPoints: [
                'Condado Portucalense criado em 1096 por D. Henrique de Borgonha',
                'D. Afonso Henriques — 1.º rei de Portugal',
                'Independência reconhecida em 1143 pelo Tratado de Zamora',
              ],
            },
          },
          {
            id: 'l2',
            topicId: 't1',
            title: 'Quiz — Formação de Portugal',
            type: 'quiz',
            difficulty: 'basico',
            estimatedMinutes: 10,
            xpReward: 75,
            isCompleted: true,
            score: 80,
            completedAt: new Date('2024-10-02'),
            content: {
              type: 'quiz',
              questions: [
                {
                  id: 'q1',
                  text: 'Quem foi o primeiro rei de Portugal?',
                  type: 'multiple-choice',
                  options: ['D. Henrique de Borgonha', 'D. Afonso Henriques', 'D. Sancho I', 'Afonso VI de Leão'],
                  correctAnswer: 1,
                  explanation: 'D. Afonso Henriques proclamou a independência de Portugal e tornou-se o seu primeiro rei.',
                },
                {
                  id: 'q2',
                  text: 'O Tratado de Zamora reconheceu a independência de Portugal em 1143.',
                  type: 'true-false',
                  options: ['Verdadeiro', 'Falso'],
                  correctAnswer: 0,
                  explanation: 'Correto! O Tratado de Zamora, assinado em 1143, reconheceu Portugal como reino independente.',
                },
                {
                  id: 'q3',
                  text: 'O Condado Portucalense foi criado em que ano?',
                  type: 'multiple-choice',
                  options: ['1066', '1096', '1139', '1143'],
                  correctAnswer: 1,
                  explanation: 'O Condado Portucalense foi criado em 1096, quando Afonso VI de Leão o doou a D. Henrique de Borgonha.',
                },
              ],
            },
          },
          {
            id: 'l3',
            topicId: 't1',
            title: 'A Reconquista Cristã — Áudio',
            type: 'audio',
            difficulty: 'intermedio',
            estimatedMinutes: 12,
            xpReward: 60,
            isCompleted: false,
            content: {
              type: 'audio',
              audioUrl: '/audio/reconquista.mp3',
              duration: 720,
              transcript: 'Nesta aula vamos explorar o processo da Reconquista Cristã em Portugal...',
              keyPoints: [
                'Reconquista: expansão cristã em território mourisco',
                'Conquista de Lisboa em 1147',
                'Fronteiras sul consolidadas no século XIII',
              ],
            },
          },
          {
            id: 'l4',
            topicId: 't1',
            title: 'Flashcards — Datas e Reis',
            type: 'flashcard',
            difficulty: 'basico',
            estimatedMinutes: 8,
            xpReward: 40,
            isCompleted: false,
            content: {
              type: 'flashcard',
              cards: [
                { id: 'fc1', front: 'Quando foi criado o Condado Portucalense?', back: '1096', example: 'Doado por Afonso VI de Leão a D. Henrique de Borgonha' },
                { id: 'fc2', front: 'Quem foi D. Afonso Henriques?', back: '1.º Rei de Portugal', example: 'Proclamou a independência em 1143' },
                { id: 'fc3', front: 'O que foi o Tratado de Zamora?', back: 'Reconhecimento da independência de Portugal (1143)', example: 'Assinado entre D. Afonso Henriques e Afonso VII de Leão' },
                { id: 'fc4', front: 'Quando foi conquistada Lisboa?', back: '1147', example: 'Com ajuda de cruzados a caminho da Terra Santa' },
              ],
            },
          },
        ],
      },
      {
        id: 't2',
        disciplineId: 'hgp-6',
        title: 'Os Descobrimentos Portugueses',
        description: 'A expansão marítima portuguesa nos séculos XV e XVI.',
        order: 2,
        isUnlocked: true,
        lessons: [
          {
            id: 'l5',
            topicId: 't2',
            title: 'Início da Expansão Marítima',
            type: 'text',
            difficulty: 'intermedio',
            estimatedMinutes: 20,
            xpReward: 70,
            isCompleted: false,
            content: {
              type: 'text',
              body: `## Os Descobrimentos Portugueses\n\nNo século XV, Portugal liderou a **expansão marítima europeia**, explorando as costas africanas e abrindo novas rotas comerciais.\n\n### Infante D. Henrique\nConhecido como o **Navegador**, D. Henrique patrocinou as primeiras expedições ao longo da costa africana a partir de **1415** (conquista de Ceuta).\n\n### Grandes Marcos\n- **1488** — Bartolomeu Dias dobra o Cabo da Boa Esperança\n- **1498** — Vasco da Gama chega à Índia\n- **1500** — Pedro Álvares Cabral chega ao Brasil\n\n> **Importância:** Os descobrimentos tornaram Portugal numa potência mundial e ligaram continentes antes isolados.`,
              keyPoints: [
                'Expansão iniciada no séc. XV com a conquista de Ceuta (1415)',
                'Infante D. Henrique — grande impulsionador das explorações',
                'Vasco da Gama abriu a rota marítima para a Índia (1498)',
              ],
            },
          },
          {
            id: 'l6',
            topicId: 't2',
            title: 'Quiz — Os Descobrimentos',
            type: 'quiz',
            difficulty: 'intermedio',
            estimatedMinutes: 15,
            xpReward: 100,
            isCompleted: false,
            content: {
              type: 'quiz',
              questions: [
                {
                  id: 'q4',
                  text: 'Quem dobrou o Cabo da Boa Esperança em 1488?',
                  type: 'multiple-choice',
                  options: ['Vasco da Gama', 'Pedro Álvares Cabral', 'Bartolomeu Dias', 'Fernão de Magalhães'],
                  correctAnswer: 2,
                  explanation: 'Bartolomeu Dias foi o primeiro navegador a dobrar o Cabo da Boa Esperança, em 1488.',
                },
                {
                  id: 'q5',
                  text: 'Vasco da Gama chegou à Índia em 1498.',
                  type: 'true-false',
                  options: ['Verdadeiro', 'Falso'],
                  correctAnswer: 0,
                  explanation: 'Correto! Vasco da Gama chegou a Calicute, na Índia, em 1498, abrindo a rota marítima para o Oriente.',
                },
              ],
            },
          },
        ],
      },
      {
        id: 't3',
        disciplineId: 'hgp-6',
        title: 'Portugal no século XX',
        description: 'O Estado Novo, o 25 de Abril e a democracia em Portugal.',
        order: 3,
        isUnlocked: false,
        lessons: [],
      },
      {
        id: 't4',
        disciplineId: 'hgp-6',
        title: 'Geografia de Portugal',
        description: 'Relevo, rios, clima e regiões naturais de Portugal.',
        order: 4,
        isUnlocked: false,
        lessons: [],
      },
    ],
  },
]

export const mockLeaderboard: LeaderboardEntry[] = [
  { userId: 'u1', name: 'Beatriz Costa', level: 12, xp: 5800, weeklyXp: 420, rank: 1 },
  { userId: 'u2', name: 'Miguel Santos', level: 11, xp: 5200, weeklyXp: 380, rank: 2 },
  { userId: 'u3', name: 'Sofia Mendes', level: 10, xp: 4600, weeklyXp: 355, rank: 3 },
  { userId: 'user-1', name: 'Marina', level: 8, xp: 3420, weeklyXp: 290, rank: 4 },
  { userId: 'u5', name: 'João Rodrigues', level: 8, xp: 3100, weeklyXp: 250, rank: 5 },
  { userId: 'u6', name: 'Inês Oliveira', level: 7, xp: 2800, weeklyXp: 200, rank: 6 },
  { userId: 'u7', name: 'Tomás Pereira', level: 6, xp: 2200, weeklyXp: 180, rank: 7 },
  { userId: 'u8', name: 'Mariana Lima', level: 5, xp: 1800, weeklyXp: 140, rank: 8 },
]

export const mockDailyStats: DailyStats[] = [
  { date: '2024-10-01', minutesStudied: 45, lessonsCompleted: 3, xpEarned: 180, disciplines: ['hgp-6'] },
  { date: '2024-10-02', minutesStudied: 30, lessonsCompleted: 2, xpEarned: 120, disciplines: ['hgp-6'] },
  { date: '2024-10-03', minutesStudied: 60, lessonsCompleted: 4, xpEarned: 240, disciplines: ['hgp-6'] },
  { date: '2024-10-04', minutesStudied: 20, lessonsCompleted: 1, xpEarned: 50, disciplines: ['hgp-6'] },
  { date: '2024-10-05', minutesStudied: 75, lessonsCompleted: 5, xpEarned: 320, disciplines: ['hgp-6'] },
  { date: '2024-10-06', minutesStudied: 0, lessonsCompleted: 0, xpEarned: 0, disciplines: [] },
  { date: '2024-10-07', minutesStudied: 50, lessonsCompleted: 3, xpEarned: 200, disciplines: ['hgp-6'] },
]

// Additional disciplines (to add when expanding)
export const additionalDisciplines: Omit<Discipline, 'topics'>[] = [
  { id: 'portugues-9', name: 'Português', subject: 'Português', year: 9, color: '#10b981', icon: '📝', totalLessons: 40, completedLessons: 0 },
  { id: 'cn-9', name: 'Ciências Naturais', subject: 'Ciências Naturais', year: 9, color: '#f59e0b', icon: '🔬', totalLessons: 36, completedLessons: 0 },
  { id: 'historia-9', name: 'História', subject: 'História', year: 9, color: '#ef4444', icon: '🏛️', totalLessons: 32, completedLessons: 0 },
  { id: 'fisico-9', name: 'Físico-Química', subject: 'Físico-Química', year: 9, color: '#a78bfa', icon: '⚗️', totalLessons: 38, completedLessons: 0 },
  { id: 'geo-9', name: 'Geografia', subject: 'Geografia', year: 9, color: '#22d3ee', icon: '🌍', totalLessons: 30, completedLessons: 0 },
]
